source "azure-arm" "autogenerated_1"{
subscription_id = "ec907711-acd7-4191-9983-9577afbe3ce1"
build_resource_group_name = "Ansible-grp-Syl"
managed_image_resource_group_name = "Ansible-grp-Syl"
managed_image_name = "apache2-srv"
os_type= "Linux"
image_publisher = "Canonical"
image_offer = "UbuntuServer"
image_sku = "18.04-LTS"     
use_interactive_auth = true
      
  azure_tags = {
  dept = "Engineering",
  task = "webserver"
  }
      
  vm_size                           = "Standard_DS2_v2"      
}
  

build {
  sources = ["source.azure-arm.autogenerated_1"]

  provisioner "shell" {     
      inline = [
      "sudo apt-get update",
      "sudo apt-get install -y apache2"
      ]
  }  
}









